openapi: 3.0.0
info:
  version: 0.0.1
  title: Day Converter Service
  description: Converts a given number to a day name.
servers: 
  - url: http://localhost:8080
    description: Local dev server

paths:
  /day/{dayNumber}:
    get:
      summary: Converts the given number to a day.
      description: Converts the given number to a dat as long as it is in the range 1 - 7. Otherwise returns an error.
      parameters: 
        - name: dayNumber
          in: path
          required: true
          description: Value you would like to conver to a day.
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 7
      responses:
        '200':
          description: The name of the day matching the number you passed in.
          content:
            application/json:
              schema:
                type: string
        '422':
          description: You must enter a whole number between 1 and 7.
    
  