openapi: 3.0.0
info:
  title: Word API
  description: A simple service that returns a random word and its corresponding definition
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
paths:
  /word:
    get:
      summary: retrieve a random word and definition
      responses:
        '200':
          description: a definition object
          content:
            application/json:
              schema:
                #referencing the definition object found at the bottom of the file
                $ref: '#/components/schemas/Definition'
components:
  schemas:
    Definition:
      properties:
        word:
          type: string
        definition:
          type: string
      required:
        - word
        - definition
  